### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by rushingbrody** [acc858/Intro-to-SE-Group-11#13]
Create a user story detailing the features of version 1.

**Comment by acc858** [comment]
User ID: 1
Title: Arthur Smith Coaching
Details: Arthur Smith wants to buy a book on football to improve his coaching ability. He navigates to Books-R-Us to find the desired book. He first creates an account using his email, creating a username and password in the process for future logins. After creating his account Arthur searches for "Football: The Art of Coaching". The book is returned, and he adds one copy of it to his cart. He navigates to check out, entering his payment and address information. The system reports the payment as successful and reports that the shipment will be delivered within 2-3 business days.

**Comment by acc858** [comment]
User Story Microsoft Word Doc has been uploaded to main along with User Story ID: 1.
