### ISSUE TITLE
Scenario-Based Modeling: Use Case Diagram

### ISSUE THREAD

**Issue by acc858** [acc858/Intro-to-SE-Group-11#17]
Create a complete Use Case diagram for showing the structure of each user class interacting with the system.

**Comment by rushingbrody** [comment]
I completed the "Use Case Diagram:

A) Seller
     • Update Selling List: The seller is able to update everything they are selling on the website
     • Login: - The seller is able to log into their account
                  - Create New Account: an extension of Log in, allows new sellers to create an account
B) User
    • Login: - The users is able to log into their account
                  - Create New Account: an extension of Log in, allows new sellers to create an account
    • View Items: - allows users to view all items that are being sold on the website
                          - Search Items: an extension of view items, allows users to search for a specific item in 
                            the list of available items
    • Update Cart: Included in "View Items," allows the user to add/remove items form their cart. While items 
                            are in the cart, the items in the inventory list are updated so people can not checkout 
                            when there are 0 items remaining
   • Make a Purchase: - Allows the User to make a purchase on the website
                                  - Checkout: included in "Make a purchase," allows the user to input in their payment 
                                     information and shipping information before checking out. 
C) Administrator: 
    • Update Inventory: The Admin is able to check to make sure the inventory is all correct
    • Access User Info: Admin is able to review User info to make sure there is no impersonation
